#' Documentation of included data source 'namelist'
#'
#' 'namelist' is a data source in the
#' \href{https://ropensci.github.io/git2rdata}{vc-format} which provides
#' names and (optionally) shortnames for IDs/codes used in other data sources.
#' Multiple languages are supported.
#'
#' @format A vc-formatted data source. As such, it corresponds to
#' a data frame with many rows and 4 variables:
#' \describe{
#'   \item{code}{A code used elsewhere.}
#'   \item{lang}{An
#'   \href{https://www.w3.org/International/articles/language-tags/index.en}{IETF BCP
#'   47 language tag}, such as \code{"en"} or \code{"nl"}, to identify
#'   the language of \code{name} and \code{shortname}.}
#'   \item{name}{The name corresponding to \code{code} and \code{lang}.}
#'   \item{shortname}{Optionally, a shorter variant of \code{name}.} }
#'
#' @section Typical way of loading:
#'
#'   \code{read_namelistmon()}
#'
#'   \code{read_namelistmon(lang = "nl")}
#'
#' @section Corresponding datafiles in the installed package:
#'
#'   \code{textdata/namelist.tsv}
#'
#'   \code{textdata/namelist.yml}
#'
#' @source
#'
#' The 'namelist' data source has got its contents from the sources of
#' several referencelists in package \code{n2khab} (see the source of those).
#'
#' @seealso \code{\link{read_namelistmon}}
#'
#' @family n2khabmon-referencelists
#'
#' @noMd
#'
#' @name namelist
NULL



#' Documentation of included data source 'schemes'
#'
#' 'schemes' is a data source in the
#' \href{https://ropensci.github.io/git2rdata}{vc-format} which provides
#' a list of (monitoring) schemes for N2KHAB monitoring programmes, together
#' with defining attributes and optional information.
#' The codes of schemes, programmes, attributes and tags
#' are explained in the
#' data source \code{\link{namelist}} (which can accommodate multiple
#' languages).
#'
#'
#' @format A vc-formatted data source. As such, it corresponds to
#' a data frame with 10 variables:
#' \describe{
#'   \item{scheme}{Code of the scheme, as a factor.
#'   This is the ID for use in diverse workflows and datasets.
#'   Corresponding names and shortnames
#'   in multiple languages are to be found in \code{\link{namelist}}.
#'   Contains no duplicates!
#'
#'   A 'scheme' refers to a monitoring setup that determines
#'   which types (habitat/RIBs) are to be investigated.
#'   }
#'   \item{programme}{Code of the programme to which the scheme belongs.
#'   The programme's code is explained by \code{\link{namelist}}.
#'   Is a factor.
#'
#'   A 'programme' refers to a N2KHAB monitoring programme.
#'   One programme can correspond to multiple schemes.
#'   At least the monitoring programmes MHQ and MNE are present.
#'   }
#'   \item{attribute_1}{The first defining attribute of the scheme.
#'   Typically, the code is explained by \code{\link{namelist}}.
#'   Is a factor.
#'   \itemize{
#'     \item{In MNE, this is used to declare the 'compartment superscheme' (scheme
#'     collection) to which the scheme belongs, and which is named after the
#'     environmental compartment (however note that the surfacewater superscheme
#'     comprises two environmental compartments).}
#'     \item{In MHQ, this is used to define the target habitat type of the
#'     monitoring scheme.}
#'   }
#'   }
#'   \item{attribute_2}{A second defining attribute of the scheme (if needed).
#'   Typically, the code is explained by \code{\link{namelist}}.
#'   Is a factor.
#'   \itemize{
#'     \item{In MNE, this provides the code of the environmental pressure to
#'     which the scheme is related.
#'     It must be represented in \code{\link{env_pressures}}.}
#'   }
#'   }
#'   \item{attribute_3}{A third defining attribute of the scheme (if needed).
#'   Typically, the code is explained by \code{\link{namelist}}.
#'   Is a factor.
#'   \itemize{
#'     \item{In MNE, this is used to declare an \strong{optional} partitioning of the
#'     scheme that would be constituted by attributes 1 and 2 alone
#'     (environmental compartment and pressure), which will hence divide the
#'     concerned types in at least two groups.
#'     This typically has to do with differences in the considered
#'     environmental variables or compatibility of interpretation.
#'
#'     It is \emph{not} meant to distinguish between different types or
#'     typegroups for inferences, so types are kept in the same scheme as
#'     long as the measured values have compatibility of interpretation.
#'     To declare which types or typegroups should be
#'     distinguished in inferences, use the \code{typegroup} variable in the
#'     \code{\link{scheme_types}} data source!}
#'   }
#'   }
#'   \item{spatial_restriction}{Optional further defining specification of a
#'   scheme (in English):
#'   spatial restrictions, superposed on the restrictions already
#'   generated by the attributes.}
#'   \item{notes}{Optional. In English. For additional notes on the scheme
#'   definition, if necessary.}
#'   \item{tag_1}{Optional tag, e.g. a categorization ID explained
#'   by \code{\link{namelist}}.
#'   \itemize{
#'     \item{In MNE, this is used to tag which schemes are focal schemes and
#'     which ones are secondary schemes.}
#'     \item{In MHQ, this is used to separate aquatic and terrestial
#'     monitoring schemes.}
#'   }
#'   }
#'   \item{tag_2}{Optional tag, e.g. a categorization ID explained
#'   by \code{\link{namelist}}.}
#'   \item{tag_3}{Optional tag, e.g. a categorization ID explained
#'   by \code{\link{namelist}}.}
#' }
#'
#' @section Typical way of loading:
#'
#'   \code{read_schemes()}
#'
#'   \code{read_schemes(lang = "nl")}
#'
#' @section Corresponding datafiles in the installed package:
#'
#'   \code{textdata/schemes.tsv}
#'
#'   \code{textdata/schemes.yml}
#'
#' @source
#'
#' \itemize{
#'     \item{For the MNE-schemes: a vc-formatted, Dutch-language data source
#'     which can be found in the
#'     \href{https://github.com/inbo/n2khab}{
#'     n2khab Github repository}:
#'     \code{misc/generate_textdata/rawraw_data/10_compmeetnet_types_milieudrukken}.
#'     This data source was originally generated in the
#'     n2khab-mne-selections repository
#'     (\samp{https://gitlab.com/florisvdh/n2khab-mne-selections}).
#'     }
#'   }
#' \itemize{
#'     \item{More information on the MHQ-schemes can be found in
#'     \href{https://doi.org/10.21436/inbor.85829488}{Westra \emph{et al.} (2022)}.
#'   }
#'  }
#'
#' @seealso \code{\link{read_schemes}}
#'
#' @family n2khabmon-referencelists
#'
#' @noMd
#'
#' @name schemes
NULL









#' Documentation of included data source 'scheme_types'
#'
#' 'scheme_types' is a data source in the
#' \href{https://ropensci.github.io/git2rdata}{vc-format} which lists
#' the types (using the type-code from \code{\link{types}}) that belong to
#' each N2KHAB monitoring scheme (using the scheme-code from
#' \code{\link{schemes}}).
#' It also defines typegroup memberships of the types within specific schemes,
#' if applicable.
#' The codes of schemes and types (and optionally: typegroups)
#' are explained in the
#' data source \code{\link{namelist}} (which can accommodate multiple
#' languages).
#'
#'
#' @format A vc-formatted data source. As such, it corresponds to
#' a data frame with 3 variables:
#' \describe{
#'   \item{scheme}{Code of the scheme, as a factor, and explained by
#'   \code{\link{namelist}}.
#'   It must be represented in \code{\link{schemes}}.
#'   }
#'   \item{type}{Code of the type, as a factor, and explained by
#'   \code{\link{namelist}}.
#'   It must be represented in \code{\link{types}}.}
#'   \item{typegroup}{An \emph{optional} code (and optionally explained by
#'   \code{\link{namelist}}),
#'   declaring the typegroup to which a type belongs \emph{within the specified
#'   scheme}.
#'   Typegroups point out which types are considered together as a group in
#'   inferences for the scheme at hand.}
#' }
#'
#' Each combination of \code{scheme} and \code{type} must be unique.
#'
#' @section Typical way of loading:
#'
#'   \code{read_scheme_types()}
#'
#'   \code{read_scheme_types(lang = "nl")}
#'
#' @section Corresponding datafiles in the installed package:
#'
#'   \code{textdata/scheme_types.tsv}
#'
#'   \code{textdata/scheme_types.yml}
#'
#' @source
#'
#' \itemize{
#'     \item{For the MNE-schemes:
#'       \itemize{
#'         \item{the link between schemes and types comes from
#'         a vc-formatted, Dutch-language data source
#'         which can be found in the
#'         \href{https://github.com/inbo/n2khab}{
#'         n2khab Github repository}:
#'         \code{misc/generate_textdata/rawraw_data/10_compmeetnet_types_milieudrukken}.
#'         This data source was originally generated in the
#'         n2khab-mne-selections repository
#'         (\samp{https://gitlab.com/florisvdh/n2khab-mne-selections}).}
#'         \item{the declaration of typegroups comes from
#'         \href{https://docs.google.com/spreadsheets/d/1n2ohvuLEK_anX37gxlanQXRGotweMVonFxKxtfTcuZI}{
#'         this googlesheet}.
#'         Currently, the typegroups are kept up to date both in the
#'         googlesheet and in the data source.}
#'         }
#'     }
#'   }
#'
#' \itemize{
#'     \item{For the MHQ-schemes, the list of sampled types is based on the report of
#'     \href{https://doi.org/10.21436/inbor.85829488}{Westra \emph{et al.} (2022)}.
#'   }
#'  }
#'
#'
#' @seealso \code{\link{read_scheme_types}}
#'
#' @family n2khabmon-referencelists
#'
#' @noMd
#'
#' @name scheme_types
NULL
